version: '2'

services:
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:9.4"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    ports:
      - "4321:5432"
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
     - "3001:3000"
    depends_on:
      - postgres
      - redis